#include "extensions.h"

PUNK_ENGINE_BEGIN
namespace Graphics {
    namespace gl {

#ifdef _WIN32
        PFNWGLSWAPINTERVALEXTPROC wglSwapIntervalEXT;
        PFNWGLGETEXTENSIONSSTRINGARBPROC wglGetExtensionsStringARB;
#elif defined __gnu_linux__
        PFNGLXCREATECONTEXTATTRIBSARBPROC glXCreateContextAttribsARB;
        //        PFNGLXCHOOSEFBCONFIGPROC glXChooseFBConfig;
        //        PFNGLXGETVISUALFROMFBCONFIGPROC glXGetVisualFromFBConfig;
        //        PFNGLXGETFBCONFIGATTRIBPROC glXGetFBConfigAttrib;
        //        PFNGLXCREATENEWCONTEXTPROC glXCreateNewContext;
        //        PFNGLXGETFBCONFIGSPROC glXGetFBConfigs;
#endif

        PFNGLGETBUFFERPARAMETERI64VPROC glGetBufferParameteri64v;
        PFNGLGETBUFFERPARAMETERIVPROC glGetBufferParameteriv;
        PFNGLGETBUFFERPARAMETERI64VPROC glGetBufferParameterui64v;
        PFNGLGETBUFFERPOINTERVPROC glGetBufferPointerv;
        PFNGLTEXPARAMETERIPROC glTexParameteri;
        PFNGLPIXELSTOREIPROC glPixelStorei;
        PFNGLPIXELSTOREFPROC glPixelStoref;
        PFNGLBLENDCOLORPROC glBlendColor;
        PFNGLBLENDEQUATIONPROC glBlendEquation;
        PFNGLBLENDEQUATIONIPROC glBlendEquationi;
        PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate;
        PFNGLBLENDEQUATIONSEPARATEIPROC glBlendEquationSeparatei;
        PFNGLENABLEIPROC glEnablei;
        PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate;
        PFNGLBLENDFUNCPROC glBlendFunc;
        PFNGLBLENDFUNCIPROC glBlendFunci;
        PFNGLACTIVETEXTUREPROC glActiveTexture;
        PFNGLCOMPRESSEDTEXIMAGE2DPROC glCompressedTexImage2D;
        PFNGLBUFFERDATAPROC glBufferData;
        PFNGLBUFFERSUBDATAPROC glBufferSubData;
        PFNGLGETBUFFERSUBDATAPROC glGetBufferSubData;
        PFNGLGENBUFFERSPROC glGenBuffers;
        PFNGLBINDBUFFERPROC glBindBuffer;
        PFNGLDELETEBUFFERSPROC glDeleteBuffers;
        PFNGLMAPBUFFERPROC glMapBuffer;
        PFNGLUNMAPBUFFERPROC glUnmapBuffer;
        PFNGLISBUFFERPROC glIsBuffer;
        PFNGLISRENDERBUFFERPROC glIsRenderbuffer;
        PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer;
        PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers;
        PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers;
        PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage;
        PFNGLGETRENDERBUFFERPARAMETERIVPROC glGetRenderbufferParameteriv;
        PFNGLISFRAMEBUFFERPROC glIsFramebuffer;
        PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer;
        PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers;
        PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers;
        PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus;
        PFNGLFRAMEBUFFERTEXTUREPROC glFramebufferTexture1D;
        PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer;
        PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glGetFramebufferAttachmentParameteriv;
        PFNGLGENERATEMIPMAPPROC glGenerateMipmap;
        PFNGLCREATESHADERPROC glCreateShader;
        PFNGLCREATEPROGRAMPROC glCreateProgram;
        PFNGLDELETESHADERPROC glDeleteShader;
        PFNGLDELETEPROGRAMPROC glDeleteProgram;
        PFNGLSHADERSOURCEPROC glShaderSource;
        PFNGLCOMPILESHADERPROC glCompileShader;
        PFNGLATTACHSHADERPROC glAttachShader;
        PFNGLDETACHSHADERPROC glDetachShader;
        PFNGLLINKPROGRAMPROC glLinkProgram;
        PFNGLUSEPROGRAMPROC glUseProgram;
        PFNGLVALIDATEPROGRAMPROC glValidateProgram;
        PFNGLUNIFORM1FPROC glUniform1f;
        PFNGLUNIFORM1FVPROC glUniform1fv;
        PFNGLUNIFORM1IPROC glUniform1i;
        PFNGLUNIFORM1IVPROC glUniform1iv;
        PFNGLUNIFORM2FPROC glUniform2f;
        PFNGLUNIFORM2FVPROC glUniform2fv;
        PFNGLUNIFORM2IVPROC glUniform2iv;
        PFNGLUNIFORM3FPROC glUniform3f;
        PFNGLUNIFORM3IVPROC glUniform3iv;
        PFNGLUNIFORM3FVPROC glUniform3fv;
        PFNGLUNIFORM3IPROC glUniform3i;
        PFNGLUNIFORM4FPROC glUniform4f;
        PFNGLUNIFORM4IVPROC glUniform4iv;
        PFNGLUNIFORM4FVPROC glUniform4fv;
        PFNGLUNIFORM4IPROC glUniform4i;
        PFNGLUNIFORMMATRIX2FVPROC glUniformMatrix2fv;
        PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv;
        PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv;
        PFNGLGETACTIVEUNIFORMPROC glGetActiveUniform;
        PFNGLGETATTACHEDSHADERSPROC glGetAttachedShaders;
        PFNGLGETSHADERSOURCEPROC glGetShaderSource;
        PFNGLGETUNIFORMFVPROC glGetUniformfv;
        PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation;
        PFNGLVERTEXATTRIB1DPROC glVertexAttrib1d;
        PFNGLVERTEXATTRIB1DVPROC glVertexAttrib1dv;
        PFNGLVERTEXATTRIB1FPROC glVertexAttrib1f;
        PFNGLVERTEXATTRIB1FVPROC glVertexAttrib1fv;
        PFNGLVERTEXATTRIB1SPROC glVertexAttrib1s;
        PFNGLVERTEXATTRIB1SVPROC glVertexAttrib1sv;
        PFNGLVERTEXATTRIB2DPROC glVertexAttrib2d;
        PFNGLVERTEXATTRIB2DVPROC glVertexAttrib2dv;
        PFNGLVERTEXATTRIB2FPROC glVertexAttrib2f;
        PFNGLVERTEXATTRIB2FVPROC glVertexAttrib2fv;
        PFNGLVERTEXATTRIB2SPROC glVertexAttrib2s;
        PFNGLVERTEXATTRIB2SVPROC glVertexAttrib2sv;
        PFNGLVERTEXATTRIB3DPROC glVertexAttrib3d;
        PFNGLVERTEXATTRIB3DVPROC glVertexAttrib3dv;
        PFNGLVERTEXATTRIB3FPROC glVertexAttrib3f;
        PFNGLVERTEXATTRIB3FVPROC glVertexAttrib3fv;
        PFNGLVERTEXATTRIB3SPROC glVertexAttrib3s;
        PFNGLVERTEXATTRIB3SVPROC glVertexAttrib3sv;
        PFNGLVERTEXATTRIB4DPROC glVertexAttrib4d;
        PFNGLVERTEXATTRIB4DVPROC glVertexAttrib4dv;
        PFNGLVERTEXATTRIB4FPROC glVertexAttrib4f;
        PFNGLVERTEXATTRIB4FVPROC glVertexAttrib4fv;
        PFNGLVERTEXATTRIB4SPROC glVertexAttrib4s;
        PFNGLVERTEXATTRIB4SVPROC glVertexAttrib4sv;
        PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
        PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation;
        PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
        PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray;
        PFNGLGETVERTEXATTRIBDVPROC glGetVertexAttribdv;
        PFNGLGETVERTEXATTRIBFVPROC glGetVertexAttribfv;
        PFNGLGETVERTEXATTRIBIVPROC glGetVertexAttribiv;
        PFNGLGETVERTEXATTRIBPOINTERVPROC glGetVertexAttribPointerv;
        PFNGLGETACTIVEATTRIBPROC glGetActiveAttrib;
        PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation;
        PFNGLDRAWRANGEELEMENTSPROC glDrawRangeElements;
        PFNGLGETSTRINGIPROC glGetStringi;
        PFNGLGETERRORPROC glGetError;
        PFNGLGETINTEGERVPROC glGetIntegerv;
        PFNGLVIEWPORTPROC glViewport;
        PFNGLCLEARCOLORPROC glClearColor;
        PFNGLENABLEPROC glEnable;
        PFNGLDISABLEPROC glDisable;
        PFNGLREADPIXELSPROC glReadPixels;
        PFNGLGETSTRINGPROC glGetString;
        PFNGLGENTEXTURESPROC glGenTextures;
        PFNGLBINDTEXTUREPROC glBindTexture;
        PFNGLTEXPARAMETERFPROC glTexParameterf;
        PFNGLTEXPARAMETERFVPROC glTexParameterfv;
        PFNGLTEXIMAGE2DPROC glTexImage2D;
        PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D;
        PFNGLDELETETEXTURESPROC glDeleteTextures;
        PFNGLDRAWBUFFERPROC glDrawBuffer;
        PFNGLREADBUFFERPROC glReadBuffer;
        PFNGLGETSHADERIVPROC glGetShaderiv;
        PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
        PFNGLGETPROGRAMIVPROC glGetProgramiv;
        PFNGLGENVERTEXARRAYSPROC glGenVertexArrays;
        PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays;
        PFNGLBINDVERTEXARRAYPROC glBindVertexArray;
        PFNGLDRAWARRAYSPROC glDrawArrays;
        PFNGLDRAWARRAYSINDIRECTPROC glDrawArraysIndirect;
        PFNGLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced;
        PFNGLDRAWELEMENTSPROC glDrawElements;
        PFNGLDRAWELEMENTSINDIRECTPROC glDrawElementsIndirect;
        PFNGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced;
        PFNGLCLEARPROC glClear;
        PFNGLTEXSUBIMAGE2DPROC glTexSubImage2D;
        PFNGLPOLYGONMODEPROC glPolygonMode;
        PFNGLFENCESYNCPROC glFenceSync;
        PFNGLWAITSYNCPROC glWaitSync;
        PFNGLDELETESYNCPROC glDeleteSync;
        PFNGLDRAWBUFFERSPROC glDrawBuffers;
        PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC glRenderbufferStorageMultisample;
        PFNGLBLITFRAMEBUFFERPROC glBlitFramebuffer;
        PFNGLDEPTHFUNCPROC glDepthFunc;
        PFNGLDEPTHMASKPROC glDepthMask;
        PFNGLPOINTSIZEPROC glPointSize;
        PFNGLPOINTPARAMETERIVPROC glPointParameteriv;
        PFNGLPOINTPARAMETERIPROC glPointParameteri;
        PFNGLPOINTPARAMETERFVPROC glPointParameterfv;
        PFNGLPOINTPARAMETERFPROC glPointParameterf;
        PFNGLCULLFACEPROC glCullFace;
        PFNGLLINEWIDTHPROC glLineWidth;
        PFNGLCLEARDEPTHFPROC glClearDepthf;
        PFNGLCLEARDEPTHPROC glClearDepth;
        PFNGLRENDERBUFFERSTORAGEMULTISAMPLECOVERAGENVPROC glRenderbufferStorageMultisampleCoverageNV;
        PFNGLFRAMEBUFFERTEXTURELAYERPROC glFramebufferTextureLayer;
        PFNGLPOLYGONOFFSETPROC glPolygonOffset;

        //GL_ARB_shading_language_include

        PFNGLNAMEDSTRINGARBPROC glNamedStringARB;
        PFNGLDELETENAMEDSTRINGARBPROC glDeleteNamedStringARB;
        PFNGLCOMPILESHADERINCLUDEARBPROC glCompileShaderIncludeARB;
        PFNGLISNAMEDSTRINGARBPROC glIsNamedStringARB;
        PFNGLGETNAMEDSTRINGARBPROC glGetNamedStringARB;
        PFNGLGETNAMEDSTRINGIVARBPROC glGetNamedStringivARB;

        void* GetGPUProcAddress(const char* name)
        {
#ifdef _WIN32
            void* res = (void*)wglGetProcAddress(name);
            if (res != 0)
                return res;
            HMODULE lib = LoadLibrary(L"OpenGL32.dll");
            res = (void*)::GetProcAddress(lib, name);
            FreeLibrary(lib);
            GetLastError();
            return res;
#elif defined __gnu_linux__
            void* res = (void*)glXGetProcAddress((const GLubyte*)name);
            return res;
#endif
        }

        void InitExtensions()
        {

#ifdef _WIN32
            wglGetExtensionsStringARB = (PFNWGLGETEXTENSIONSSTRINGARBPROC)GetGPUProcAddress("wglGetExtensionsStringARB");
            wglSwapIntervalEXT = (PFNWGLSWAPINTERVALEXTPROC)GetGPUProcAddress("wglSwapIntervalEXT");
#endif
            glTexParameterf = (PFNGLTEXPARAMETERFPROC)GetGPUProcAddress("glTexParameterf");
            glBindTexture = (PFNGLBINDTEXTUREPROC)GetGPUProcAddress("glBindTexture");
            glGetIntegerv = (PFNGLGETINTEGERVPROC)GetGPUProcAddress("glGetIntegerv");
            glGetStringi = (PFNGLGETSTRINGIPROC)GetGPUProcAddress("glGetStringi");
            glGetError = (PFNGLGETERRORPROC)GetGPUProcAddress("glGetError");
            glDrawRangeElements = (PFNGLDRAWRANGEELEMENTSPROC)GetGPUProcAddress("glDrawRangeElements");
            //glViewport = (PFNGLVIEWPORTPROC)GetGPUProcAddress("glViewport");
            glClearColor = (PFNGLCLEARCOLORPROC)GetGPUProcAddress("glClearColor");
            glEnable = (PFNGLENABLEPROC)GetGPUProcAddress("glEnable");
            glDisable = (PFNGLDISABLEPROC)GetGPUProcAddress("glDisable");
            glReadPixels = (PFNGLREADPIXELSPROC)GetGPUProcAddress("glReadPixels");
            glGetString = (PFNGLGETSTRINGPROC)GetGPUProcAddress("glGetString");
            glGenTextures = (PFNGLGENTEXTURESPROC)GetGPUProcAddress("glGenTextures");
            glBindTexture = (PFNGLBINDTEXTUREPROC)GetGPUProcAddress("glBindTexture");
            glTexParameterf = (PFNGLTEXPARAMETERFPROC)GetGPUProcAddress("glTexParameterf");
            glTexParameterfv = (PFNGLTEXPARAMETERFVPROC)GetGPUProcAddress("glTexParameterfv");
            glTexImage2D = (PFNGLTEXIMAGE2DPROC)GetGPUProcAddress("glTexImage2D");
            glFramebufferTexture2D= (PFNGLFRAMEBUFFERTEXTURE2DPROC)GetGPUProcAddress("glFramebufferTexture2D");
            glDeleteTextures = (PFNGLDELETETEXTURESPROC)GetGPUProcAddress("glDeleteTextures");
            glDrawBuffer = (PFNGLDRAWBUFFERPROC)GetGPUProcAddress("glDrawBuffer");
            glReadBuffer = (PFNGLREADBUFFERPROC)GetGPUProcAddress("glReadBuffer");
            glBufferData = (PFNGLBUFFERDATAPROC)GetGPUProcAddress("glBufferData");
            glBufferSubData = (PFNGLBUFFERSUBDATAPROC)GetGPUProcAddress("glBufferSubData");
            glGetBufferSubData = (PFNGLGETBUFFERSUBDATAPROC)GetGPUProcAddress("glGetBufferSubData");
            glGenBuffers = (PFNGLGENBUFFERSPROC)GetGPUProcAddress("glGenBuffers");
            glBindBuffer = (PFNGLBINDBUFFERPROC)GetGPUProcAddress("glBindBuffer");
            glDeleteBuffers = (PFNGLDELETEBUFFERSPROC)GetGPUProcAddress("glDeleteBuffers");
            glMapBuffer = (PFNGLMAPBUFFERPROC)GetGPUProcAddress("glMapBuffer");
            glUnmapBuffer = (PFNGLUNMAPBUFFERPROC)GetGPUProcAddress("glUnmapBuffer");
            glIsBuffer = (PFNGLISBUFFERPROC)GetGPUProcAddress("glIsBuffer");
            glIsRenderbuffer = (PFNGLISRENDERBUFFERPROC)GetGPUProcAddress("glIsRenderbuffer");
            glBindRenderbuffer = (PFNGLBINDRENDERBUFFERPROC)GetGPUProcAddress("glBindRenderbuffer");
            glDeleteRenderbuffers = (PFNGLDELETERENDERBUFFERSPROC)GetGPUProcAddress("glDeleteRenderbuffers");
            glGenRenderbuffers = (PFNGLGENRENDERBUFFERSPROC)GetGPUProcAddress("glGenRenderbuffers");
            glRenderbufferStorage = (PFNGLRENDERBUFFERSTORAGEPROC)GetGPUProcAddress("glRenderbufferStorage");
            glGetRenderbufferParameteriv = (PFNGLGETRENDERBUFFERPARAMETERIVPROC)GetGPUProcAddress("glGetRenderbufferParameteriv");
            glIsFramebuffer = (PFNGLISFRAMEBUFFERPROC)GetGPUProcAddress("glIsFramebuffer");
            glBindFramebuffer = (PFNGLBINDFRAMEBUFFERPROC)GetGPUProcAddress("glBindFramebuffer");
            glDeleteFramebuffers = (PFNGLDELETEFRAMEBUFFERSPROC)GetGPUProcAddress("glDeleteFramebuffers");
            glGenFramebuffers =  (PFNGLGENFRAMEBUFFERSPROC)GetGPUProcAddress("glGenFramebuffers");
            glCheckFramebufferStatus = (PFNGLCHECKFRAMEBUFFERSTATUSPROC)GetGPUProcAddress("glCheckFramebufferStatus");
            glFramebufferRenderbuffer = (PFNGLFRAMEBUFFERRENDERBUFFERPROC)GetGPUProcAddress("glFramebufferRenderbuffer");
            glGetFramebufferAttachmentParameteriv = (PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC)GetGPUProcAddress("glGetFramebufferAttachmentParameteriv");
            glGenerateMipmap = (PFNGLGENERATEMIPMAPPROC)GetGPUProcAddress("glGenerateMipmap");;
            glCreateShader = (PFNGLCREATESHADERPROC)GetGPUProcAddress("glCreateShader");
            glCreateProgram = (PFNGLCREATEPROGRAMPROC)GetGPUProcAddress("glCreateProgram");
            glDeleteProgram = (PFNGLDELETEPROGRAMPROC)GetGPUProcAddress("glDeleteProgram");
            glDeleteShader = (PFNGLDELETESHADERPROC)GetGPUProcAddress("glDeleteShader");
            glShaderSource = (PFNGLSHADERSOURCEPROC)GetGPUProcAddress("glShaderSource");
            glCompileShader = (PFNGLCOMPILESHADERPROC)GetGPUProcAddress("glCompileShader");
            glAttachShader = (PFNGLATTACHSHADERPROC)GetGPUProcAddress("glAttachShader");
            glDetachShader = (PFNGLDETACHSHADERPROC)GetGPUProcAddress("glDetachShader");
            glLinkProgram = (PFNGLLINKPROGRAMPROC)GetGPUProcAddress("glLinkProgram");
            glUseProgram = (PFNGLUSEPROGRAMPROC)GetGPUProcAddress("glUseProgram");
            glValidateProgram = (PFNGLVALIDATEPROGRAMPROC)GetGPUProcAddress("glValidateProgram");
            glUniform1f = (PFNGLUNIFORM1FPROC)GetGPUProcAddress("glUniform1f");
            glUniform1fv = (PFNGLUNIFORM1FVPROC )GetGPUProcAddress("glUniform1fv");
            glUniform1i = (PFNGLUNIFORM1IPROC )GetGPUProcAddress("glUniform1i");
            glUniform1iv = (PFNGLUNIFORM1IVPROC )GetGPUProcAddress("glUniform1iv");
            glUniform2f = (PFNGLUNIFORM2FPROC )GetGPUProcAddress("glUniform2f");
            glUniform2fv = (PFNGLUNIFORM2FVPROC )GetGPUProcAddress("glUniform2fv");
            glUniform2iv = (PFNGLUNIFORM2IVPROC )GetGPUProcAddress("glUniform2iv");
            glUniform3f = (PFNGLUNIFORM3FPROC )GetGPUProcAddress("glUniform3f");
            glUniform3iv = (PFNGLUNIFORM3IVPROC )GetGPUProcAddress("glUniform3iv");
            glUniform3fv = (PFNGLUNIFORM3FVPROC )GetGPUProcAddress("glUniform3fv");
            glUniform3i = (PFNGLUNIFORM3IPROC )GetGPUProcAddress("glUniform3i");
            glUniform4f = (PFNGLUNIFORM4FPROC )GetGPUProcAddress("glUniform4f");
            glUniform4iv = (PFNGLUNIFORM4IVPROC )GetGPUProcAddress("glUniform4iv");
            glUniform4fv = (PFNGLUNIFORM4FVPROC )GetGPUProcAddress("glUniform4fv");
            glUniform4i = (PFNGLUNIFORM4IPROC )GetGPUProcAddress("glUniform4i");
            glGetActiveUniform = (PFNGLGETACTIVEUNIFORMPROC )GetGPUProcAddress("glGetActiveUniform");
            glGetAttachedShaders = (PFNGLGETATTACHEDSHADERSPROC)GetGPUProcAddress("glGetAttachedShaders");
            glGetShaderSource = (PFNGLGETSHADERSOURCEPROC )GetGPUProcAddress("glGetShaderSource");
            glGetUniformfv = (PFNGLGETUNIFORMFVPROC )GetGPUProcAddress("glGetUniformfv");
            glGetUniformLocation = (PFNGLGETUNIFORMLOCATIONPROC )GetGPUProcAddress("glGetUniformLocation");
            glVertexAttrib1d = (PFNGLVERTEXATTRIB1DPROC)GetGPUProcAddress("glVertexAttrib1d");
            glVertexAttrib1dv = (PFNGLVERTEXATTRIB1DVPROC)GetGPUProcAddress("glVertexAttrib1dv");
            glVertexAttrib1f = (PFNGLVERTEXATTRIB1FPROC)GetGPUProcAddress("glVertexAttrib1f");
            glVertexAttrib1fv = (PFNGLVERTEXATTRIB1FVPROC)GetGPUProcAddress("glVertexAttrib1fv");
            glVertexAttrib1s = (PFNGLVERTEXATTRIB1SPROC )GetGPUProcAddress("glVertexAttrib1s");
            glVertexAttrib1sv = (PFNGLVERTEXATTRIB1SVPROC )GetGPUProcAddress("glVertexAttrib1sv");
            glVertexAttrib2d = (PFNGLVERTEXATTRIB2DPROC )GetGPUProcAddress("glVertexAttrib2d");
            glVertexAttrib2dv = (PFNGLVERTEXATTRIB2DVPROC )GetGPUProcAddress("glVertexAttrib2dv");
            glVertexAttrib2f = (PFNGLVERTEXATTRIB2FPROC )GetGPUProcAddress("glVertexAttrib2f");
            glVertexAttrib2fv = (PFNGLVERTEXATTRIB2FVPROC )GetGPUProcAddress("glVertexAttrib2fv");
            glVertexAttrib2s = (PFNGLVERTEXATTRIB2SPROC )GetGPUProcAddress("glVertexAttrib2s");
            glVertexAttrib2sv = (PFNGLVERTEXATTRIB2SVPROC )GetGPUProcAddress("glVertexAttrib2sv");
            glVertexAttrib3d = (PFNGLVERTEXATTRIB3DPROC )GetGPUProcAddress("glVertexAttrib3d");
            glVertexAttrib3dv = (PFNGLVERTEXATTRIB3DVPROC )GetGPUProcAddress("glVertexAttrib3dv");
            glVertexAttrib3f = (PFNGLVERTEXATTRIB3FPROC )GetGPUProcAddress("glVertexAttrib3f");
            glVertexAttrib3fv = (PFNGLVERTEXATTRIB3FVPROC )GetGPUProcAddress("glVertexAttrib3fv");
            glVertexAttrib3s = (PFNGLVERTEXATTRIB3SPROC )GetGPUProcAddress("glVertexAttrib3s");
            glVertexAttrib3sv = (PFNGLVERTEXATTRIB3SVPROC )GetGPUProcAddress("glVertexAttrib3sv");
            glVertexAttrib4d = (PFNGLVERTEXATTRIB4DPROC )GetGPUProcAddress("glVertexAttrib4d");
            glVertexAttrib4dv = (PFNGLVERTEXATTRIB4DVPROC )GetGPUProcAddress("glVertexAttrib4dv");
            glVertexAttrib4f = (PFNGLVERTEXATTRIB4FPROC )GetGPUProcAddress("glVertexAttrib4f");
            glVertexAttrib4fv = (PFNGLVERTEXATTRIB4FVPROC )GetGPUProcAddress("glVertexAttrib4fv");
            glVertexAttrib4s = (PFNGLVERTEXATTRIB4SPROC )GetGPUProcAddress("glVertexAttrib4s");
            glVertexAttrib4sv = (PFNGLVERTEXATTRIB4SVPROC )GetGPUProcAddress("glVertexAttrib4sv");
            glVertexAttribPointer = (PFNGLVERTEXATTRIBPOINTERPROC )GetGPUProcAddress("glVertexAttribPointer");
            glBindAttribLocation = (PFNGLBINDATTRIBLOCATIONPROC )GetGPUProcAddress("glBindAttribLocation");
            glEnableVertexAttribArray = (PFNGLENABLEVERTEXATTRIBARRAYPROC )GetGPUProcAddress("glEnableVertexAttribArray");
            glDisableVertexAttribArray = (PFNGLDISABLEVERTEXATTRIBARRAYPROC )GetGPUProcAddress("glDisableVertexAttribArray");
            glGetVertexAttribdv = (PFNGLGETVERTEXATTRIBDVPROC )GetGPUProcAddress("glGetVertexAttribdv");
            glGetVertexAttribfv = (PFNGLGETVERTEXATTRIBFVPROC )GetGPUProcAddress("glGetVertexAttribfv");
            glGetVertexAttribiv = (PFNGLGETVERTEXATTRIBIVPROC )GetGPUProcAddress("glGetVertexAttribiv");
            glGetVertexAttribPointerv = (PFNGLGETVERTEXATTRIBPOINTERVPROC )GetGPUProcAddress("glGetVertexAttribPointerv");
            glGetActiveAttrib = (PFNGLGETACTIVEATTRIBPROC )GetGPUProcAddress("glGetActiveAttrib");
            glUniformMatrix2fv = (PFNGLUNIFORMMATRIX2FVPROC)GetGPUProcAddress("glUniformMatrix2fv");
            glUniformMatrix3fv = (PFNGLUNIFORMMATRIX3FVPROC)GetGPUProcAddress("glUniformMatrix3fv");
            glUniformMatrix4fv = (PFNGLUNIFORMMATRIX4FVPROC)GetGPUProcAddress("glUniformMatrix4fv");
            glGetAttribLocation = (PFNGLGETATTRIBLOCATIONPROC)GetGPUProcAddress("glGetAttribLocation");
            glGetShaderiv = (PFNGLGETSHADERIVPROC)GetGPUProcAddress("glGetShaderiv");
            glGetShaderInfoLog = (PFNGLGETSHADERINFOLOGPROC)GetGPUProcAddress("glGetShaderInfoLog");
            glGetProgramiv = (PFNGLGETPROGRAMIVPROC)GetGPUProcAddress("glGetProgramiv");
            glGenVertexArrays = (PFNGLGENVERTEXARRAYSPROC)GetGPUProcAddress("glGenVertexArrays");
            glDeleteVertexArrays = (PFNGLDELETEVERTEXARRAYSPROC)GetGPUProcAddress("glDeleteVertexArrays");
            glBindVertexArray = (PFNGLBINDVERTEXARRAYPROC)GetGPUProcAddress("glBindVertexArray");
            glDrawArrays = (PFNGLDRAWARRAYSPROC)GetGPUProcAddress("glDrawArrays");
            glDrawArraysIndirect = (PFNGLDRAWARRAYSINDIRECTPROC)GetGPUProcAddress("glDrawArraysIndirect");
            glDrawArraysInstanced = (PFNGLDRAWARRAYSINSTANCEDPROC)GetGPUProcAddress("glDrawArraysInstanced");
            glDrawElements = (PFNGLDRAWELEMENTSPROC)GetGPUProcAddress("glDrawElements");
            glDrawElementsIndirect = (PFNGLDRAWELEMENTSINDIRECTPROC)GetGPUProcAddress("glDrawElementsIndirect");
            glDrawElementsInstanced = (PFNGLDRAWELEMENTSINSTANCEDPROC)GetGPUProcAddress("glDrawElementsInstanced");
            glClear = (PFNGLCLEARPROC)GetGPUProcAddress("glClear");
            glCompressedTexImage2D = (PFNGLCOMPRESSEDTEXIMAGE2DPROC)GetGPUProcAddress("glCompressedTexImage2D");
            glActiveTexture = (PFNGLACTIVETEXTUREPROC)GetGPUProcAddress("glActiveTexture");
            glGetProgramiv = (PFNGLGETPROGRAMIVPROC)GetGPUProcAddress("glGetProgramiv");
            glBlendFunc = (PFNGLBLENDFUNCPROC)GetGPUProcAddress("glBlendFunc");
            glBlendEquation = (PFNGLBLENDEQUATIONPROC)GetGPUProcAddress("glBlendEquation");
            glBlendEquationi = (PFNGLBLENDEQUATIONIPROC)GetGPUProcAddress("glBlendEquationi");
            glBlendEquationSeparate = (PFNGLBLENDEQUATIONSEPARATEPROC)GetGPUProcAddress("glBlendEquationSeparate");
            glBlendEquationSeparatei = (PFNGLBLENDEQUATIONSEPARATEIPROC)GetGPUProcAddress("glBlendEquationSeparatei");
            glEnablei = (PFNGLENABLEIPROC)GetGPUProcAddress("glEnablei");
            glBlendFuncSeparate = (PFNGLBLENDFUNCSEPARATEPROC)GetGPUProcAddress("glBlendFuncSeparate");
            glBlendFunci = (PFNGLBLENDFUNCIPROC)GetGPUProcAddress("glBlendFunci");
            glBlendColor = (PFNGLBLENDCOLORPROC)GetGPUProcAddress("glBlendColor");
            glPixelStorei = (PFNGLPIXELSTOREIPROC)GetGPUProcAddress("glPixelStorei");
            glPixelStoref = (PFNGLPIXELSTOREFPROC)GetGPUProcAddress("glPixelStoref");
            glTexParameteri = (PFNGLTEXPARAMETERIPROC)GetGPUProcAddress("glTexParameteri");
            glGenerateMipmap = (PFNGLGENERATEMIPMAPPROC)GetGPUProcAddress("glGenerateMipmap");
            glTexSubImage2D = (PFNGLTEXSUBIMAGE2DPROC)GetGPUProcAddress("glTexSubImage2D");
            glPolygonMode = (PFNGLPOLYGONMODEPROC)GetGPUProcAddress("glPolygonMode");
            glGetBufferParameteri64v = (PFNGLGETBUFFERPARAMETERI64VPROC)GetGPUProcAddress("glGetBufferParameteri64v");
            glGetBufferParameteriv = (PFNGLGETBUFFERPARAMETERIVPROC)GetGPUProcAddress("glGetBufferParameteriv");
            glGetBufferParameterui64v = (PFNGLGETBUFFERPARAMETERI64VPROC)GetGPUProcAddress("glGetBufferParameterui64v");
            glGetBufferPointerv = (PFNGLGETBUFFERPOINTERVPROC)GetGPUProcAddress("glGetBufferPointerv");
            glFenceSync = (PFNGLFENCESYNCPROC )GetGPUProcAddress("glFenceSync");
            glWaitSync = (PFNGLWAITSYNCPROC)GetGPUProcAddress("glWaitSync");
            glDeleteSync = (PFNGLDELETESYNCPROC)GetGPUProcAddress("glDeleteSync");
            glDrawBuffers = (PFNGLDRAWBUFFERSPROC)GetGPUProcAddress("glDrawBuffers");
            glRenderbufferStorageMultisample = (PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC)GetGPUProcAddress("glRenderbufferStorageMultisample");
            glBlitFramebuffer = (PFNGLBLITFRAMEBUFFERPROC)GetGPUProcAddress("glBlitFramebuffer");
            glDepthFunc = (PFNGLDEPTHFUNCPROC)GetGPUProcAddress("glDepthFunc");
            glDepthMask = (PFNGLDEPTHMASKPROC)GetGPUProcAddress("glDepthMask");
            glPointSize = (PFNGLPOINTSIZEPROC)GetGPUProcAddress("glPointSize");
            glPointParameteriv = (PFNGLPOINTPARAMETERIVPROC)GetGPUProcAddress("glPointParameteriv");
            glPointParameteri = (PFNGLPOINTPARAMETERIPROC)GetGPUProcAddress("glPointParameteri");
            glPointParameterfv = (PFNGLPOINTPARAMETERFVPROC)GetGPUProcAddress("glPointParameterfv");
            glPointParameterf = (PFNGLPOINTPARAMETERFPROC)GetGPUProcAddress("glPointParameterf");
            glCullFace = (PFNGLCULLFACEPROC)GetGPUProcAddress("glCullFace");
            glLineWidth = (PFNGLLINEWIDTHPROC)GetGPUProcAddress("glLineWidth");
            glClearDepthf = (PFNGLCLEARDEPTHFPROC)GetGPUProcAddress("glClearDepthf");
            glClearDepth = (PFNGLCLEARDEPTHPROC)GetGPUProcAddress("glClearDepth");
            glRenderbufferStorageMultisampleCoverageNV = (PFNGLRENDERBUFFERSTORAGEMULTISAMPLECOVERAGENVPROC)GetGPUProcAddress("glRenderbufferStorageMultisampleCoverageNV");
            glFramebufferTextureLayer = (PFNGLFRAMEBUFFERTEXTURELAYERPROC)GetGPUProcAddress("glFramebufferTextureLayer");
            glPolygonOffset = (PFNGLPOLYGONOFFSETPROC)GetGPUProcAddress("glPolygonOffset");

            // GL_ARB_shading_language_include
            //if (IsShaderIncludeSupported(this))
            {
                glNamedStringARB = (PFNGLNAMEDSTRINGARBPROC)GetGPUProcAddress("glNamedStringARB");
                glDeleteNamedStringARB = (PFNGLDELETENAMEDSTRINGARBPROC)GetGPUProcAddress("glDeleteNamedStringARB");
                glCompileShaderIncludeARB = (PFNGLCOMPILESHADERINCLUDEARBPROC)GetGPUProcAddress("glCompileShaderIncludeARB");
                glIsNamedStringARB = (PFNGLISNAMEDSTRINGARBPROC)GetGPUProcAddress("glIsNamedStringARB");
                glGetNamedStringARB = (PFNGLGETNAMEDSTRINGARBPROC)GetGPUProcAddress("glGetNamedStringARB");
                glGetNamedStringivARB = (PFNGLGETNAMEDSTRINGIVARBPROC)GetGPUProcAddress("glGetNamedStringivARB");
            }
        }
    }
}
PUNK_ENGINE_END
