######################################################################
# Automatically generated by qmake (2.01a) ?? 25. ??? 19:53:26 2013
######################################################################

include(../punk_common.pri)

CONFIG += dll
TEMPLATE = lib
TARGET = punk_physics

LIBS += -L$${LIBDIR} -lpunk_error -lpunk_string -lpunk_core 

INCLUDEPATH += ../../../source

