######################################################################
# Automatically generated by qmake (2.01a) ?? 25. ??? 19:53:26 2013
######################################################################

include(../punk_common.pri)

CONFIG += dll
CONFIG -= qt
TEMPLATE = lib
TARGET = punk_error

INCLUDEPATH += ../../../source

HEADERS += \
    ../../../source/error/module.h \
    ../../../source/error/punk_error.h

SOURCES += \
    ../../../source/error/punk_error.cpp

