######################################################################
# Automatically generated by qmake (2.01a) ?? 25. ??? 19:53:26 2013
######################################################################

include(../punk_common.pri)

CONFIG += dll
TEMPLATE = lib
TARGET = punk_graphics

DEFINES += USE_OPENGL

unix {
    LIBS += -lX11 -lGL
}

win32 {
    LIBS += -lopengl32 -lgdi32
}

LIBS += -L$${LIBDIR} -lpunk_error -lpunk_string -lpunk_core -lpunk_system -lpunk_image -lpunk_math

INCLUDEPATH += ../../../source

HEADERS += \
    ../../../source/graphics/attributes/module.h \
    ../../../source/graphics/blending/blend_function.h \
    ../../../source/graphics/blending/gl_blending.h \
    ../../../source/graphics/blending/module.h \
    ../../../source/graphics/buffers/ibo.h \
    ../../../source/graphics/buffers/ibufffer_object.h \
    ../../../source/graphics/buffers/module.h \
    ../../../source/graphics/buffers/pbo.h \
    ../../../source/graphics/buffers/template_buffer.h \
    ../../../source/graphics/buffers/vbo.h \
    ../../../source/graphics/canvas/canvas.h \
    ../../../source/graphics/canvas/canvas_desciption.h \
    ../../../source/graphics/canvas/icanvas.h \
    ../../../source/graphics/canvas/module.h \
    ../../../source/graphics/error/graphics_error.h \
    ../../../source/graphics/error/module.h \
    ../../../source/graphics/fog/fog.h \
    ../../../source/graphics/fog/fog_mode.h \
    ../../../source/graphics/fog/module.h \
    ../../../source/graphics/frame/frame.h \
    ../../../source/graphics/frame/iframe.h \
    ../../../source/graphics/frame/module.h \
    ../../../source/graphics/frame_buffer/gl_frame_buffer/gl_color_render_buffer.h \
    ../../../source/graphics/frame_buffer/gl_frame_buffer/gl_depth_render_buffer.h \
    ../../../source/graphics/frame_buffer/gl_frame_buffer/gl_frame_buffer.h \
    ../../../source/graphics/frame_buffer/gl_frame_buffer/gl_frame_buffer_config.h \
    ../../../source/graphics/frame_buffer/gl_frame_buffer/gl_frame_buffer_convert.h \
    ../../../source/graphics/frame_buffer/gl_frame_buffer/module.h \
    ../../../source/graphics/frame_buffer/color_render_buffer.h \
    ../../../source/graphics/frame_buffer/depth_render_buffer.h \
    ../../../source/graphics/frame_buffer/frame_buffer.h \
    ../../../source/graphics/frame_buffer/frame_buffer_config.h \
    ../../../source/graphics/frame_buffer/frame_buffer_target.h \
    ../../../source/graphics/frame_buffer/iframe_buffer.h \
    ../../../source/graphics/frame_buffer/irender_buffer.h \
    ../../../source/graphics/frame_buffer/module.h \
    ../../../source/graphics/frame_buffer/render_buffer.h \
    ../../../source/graphics/frame_buffer/render_buffer_config.h \
    ../../../source/graphics/lighting/light_model.h \
    ../../../source/graphics/lighting/light_parameters.h \
    ../../../source/graphics/lighting/module.h \
    ../../../source/graphics/material/gpu_material.h \
    ../../../source/graphics/material/module.h \
    ../../../source/graphics/nvtristrip/nv_tri_strip.h \
    ../../../source/graphics/nvtristrip/nv_tri_strip_objects.h \
    ../../../source/graphics/nvtristrip/vertex_cache.h \
    ../../../source/graphics/opengl/error/gl_error_check.h \
    ../../../source/graphics/opengl/error/gl_exceptions.h \
    ../../../source/graphics/opengl/error/module.h \
    ../../../source/graphics/opengl/gl/glcorearb.h \
    ../../../source/graphics/opengl/gl/glxext.h \
    ../../../source/graphics/opengl/gl/wglext.h \
    ../../../source/graphics/opengl/extensions.h \
    ../../../source/graphics/opengl/module.h \
    ../../../source/graphics/painter/gl_painter/gl_paint_device.h \
    ../../../source/graphics/painter/gl_painter/gl_paint_engine.h \
    ../../../source/graphics/painter/gl_painter/gl_painter.h \
    ../../../source/graphics/painter/gl_painter/module.h \
    ../../../source/graphics/painter/brush.h \
    ../../../source/graphics/painter/module.h \
    ../../../source/graphics/painter/paint_device.h \
    ../../../source/graphics/painter/paint_engine.h \
    ../../../source/graphics/painter/painter.h \
    ../../../source/graphics/painter/pen.h \
    ../../../source/graphics/primitives/gl_primitive/gl_attribute_configer.h \
    ../../../source/graphics/primitives/gl_primitive/gl_batch.h \
    ../../../source/graphics/primitives/gl_primitive/gl_primitive_type.h \
    ../../../source/graphics/primitives/gl_primitive/gl_renderable.h \
    ../../../source/graphics/primitives/gl_primitive/gl_vertex_array_object.h \
    ../../../source/graphics/primitives/gl_primitive/gl_vertex_component_type.h \
    ../../../source/graphics/primitives/gl_primitive/module.h \
    ../../../source/graphics/primitives/cube_mesh.h \
    ../../../source/graphics/primitives/frustum_mesh.h \
    ../../../source/graphics/primitives/grid_object.h \
    ../../../source/graphics/primitives/iindex_array.h \
    ../../../source/graphics/primitives/ilines.h \
    ../../../source/graphics/primitives/index_array.h \
    ../../../source/graphics/primitives/ipoints.h \
    ../../../source/graphics/primitives/irenderable.h \
    ../../../source/graphics/primitives/itriangle_fans.h \
    ../../../source/graphics/primitives/itriangle_strip.h \
    ../../../source/graphics/primitives/itriangles.h \
    ../../../source/graphics/primitives/ivertex_array.h \
    ../../../source/graphics/primitives/lines.h \
    ../../../source/graphics/primitives/module.h \
    ../../../source/graphics/primitives/points.h \
    ../../../source/graphics/primitives/primitive_type.h \
    ../../../source/graphics/primitives/quad_mesh.h \
    ../../../source/graphics/primitives/renderable.h \
    ../../../source/graphics/primitives/scaled_grid.h \
    ../../../source/graphics/primitives/skin_mesh.h \
    ../../../source/graphics/primitives/sphere_mesh.h \
    ../../../source/graphics/primitives/static_mesh.h \
    ../../../source/graphics/primitives/triangle_fans.h \
    ../../../source/graphics/primitives/triangle_strip.h \
    ../../../source/graphics/primitives/triangles.h \
    ../../../source/graphics/primitives/vertex.h \
    ../../../source/graphics/primitives/vertex_array.h \
    ../../../source/graphics/primitives/vertex_component.h \
#    ../../../source/graphics/render/gl_render/fs_bump.h \
#    ../../../source/graphics/render/gl_render/fs_bump_diffuse_color.h \
#    ../../../source/graphics/render/gl_render/fs_bump_diffuse_color_specular.h \
#    ../../../source/graphics/render/gl_render/fs_bump_shadow_map.h \
#    ../../../source/graphics/render/gl_render/fs_bump_tex_diffuse.h \
#    ../../../source/graphics/render/gl_render/fs_bump_tex_diffuse_specular.h \
#    ../../../source/graphics/render/gl_render/fs_depth.h \
#    ../../../source/graphics/render/gl_render/fs_grass.h \
#    ../../../source/graphics/render/gl_render/fs_gui.h \
#    ../../../source/graphics/render/gl_render/fs_light.h \
#    ../../../source/graphics/render/gl_render/fs_painter.h \
#    ../../../source/graphics/render/gl_render/fs_per_fragment_lighting_diffuse_specular.h \
#    ../../../source/graphics/render/gl_render/fs_per_fragment_lighting_tex_diffuse_specular.h \
#    ../../../source/graphics/render/gl_render/fs_per_vertex_lighting_diffuse_shadow_simple.h \
#    ../../../source/graphics/render/gl_render/fs_per_vertex_lighting_tex_diffuse.h \
#    ../../../source/graphics/render/gl_render/fs_pfl_diffuse_simple_shadow.h \
#    ../../../source/graphics/render/gl_render/fs_shadow_single.h \
#    ../../../source/graphics/render/gl_render/fs_skinning.h \
#    ../../../source/graphics/render/gl_render/fs_solid_textured.h \
#    ../../../source/graphics/render/gl_render/fs_solid_textured_2d_array.h \
#    ../../../source/graphics/render/gl_render/fs_solid_vertex_color.h \
#    ../../../source/graphics/render/gl_render/fs_terrain.h \
#    ../../../source/graphics/render/gl_render/fs_text_solid.h \
    ../../../source/graphics/render/gl_render/gl_fog_parameters.h \
    ../../../source/graphics/render/gl_render/gl_ishader.h \
    ../../../source/graphics/render/gl_render/gl_light_per_fragment_diffuse.h \
    ../../../source/graphics/render/gl_render/gl_light_per_fragment_diffuse_skinning.h \
    ../../../source/graphics/render/gl_render/gl_light_per_fragment_texture_diffuse.h \
    ../../../source/graphics/render/gl_render/gl_light_source_parameters.h \
    ../../../source/graphics/render/gl_render/gl_material_parameters.h \
    ../../../source/graphics/render/gl_render/gl_no_light_solid_color.h \
    ../../../source/graphics/render/gl_render/gl_rc_dynamic.h \
    ../../../source/graphics/render/gl_render/gl_rc_instances.h \
    ../../../source/graphics/render/gl_render/gl_render_context.h \
    ../../../source/graphics/render/gl_render/gl_render_context_base.h \
    ../../../source/graphics/render/gl_render/gl_shader.h \
    ../../../source/graphics/render/gl_render/gl_shader_base.h \
    ../../../source/graphics/render/gl_render/gl_shader_cooker.h \
    ../../../source/graphics/render/gl_render/gl_shader_type.h \
    ../../../source/graphics/render/gl_render/module.h \
#    ../../../source/graphics/render/gl_render/vs_bump.h \
#    ../../../source/graphics/render/gl_render/vs_bump_diffuse_color.h \
#    ../../../source/graphics/render/gl_render/vs_bump_diffuse_color_specular.h \
#    ../../../source/graphics/render/gl_render/vs_bump_shadow_map.h \
#    ../../../source/graphics/render/gl_render/vs_bump_tex_diffuse.h \
#    ../../../source/graphics/render/gl_render/vs_bump_tex_diffuse_specular.h \
#    ../../../source/graphics/render/gl_render/vs_depth.h \
#    ../../../source/graphics/render/gl_render/vs_grass.h \
#    ../../../source/graphics/render/gl_render/vs_gui.h \
#    ../../../source/graphics/render/gl_render/vs_light.h \
#    ../../../source/graphics/render/gl_render/vs_painter.h \
#    ../../../source/graphics/render/gl_render/vs_particle.h \
#    ../../../source/graphics/render/gl_render/vs_particle_system.h \
#    ../../../source/graphics/render/gl_render/vs_per_fragment_lighting_diffuse.h \
#    ../../../source/graphics/render/gl_render/vs_per_fragment_lighting_diffuse_specular.h \
#    ../../../source/graphics/render/gl_render/vs_per_fragment_lighting_tex_diffuse.h \
#    ../../../source/graphics/render/gl_render/vs_per_fragment_lighting_tex_diffuse_specular.h \
#    ../../../source/graphics/render/gl_render/vs_per_vertex_lighting.h \
#    ../../../source/graphics/render/gl_render/vs_per_vertex_lighting_diffuse.h \
#    ../../../source/graphics/render/gl_render/vs_per_vertex_lighting_diffuse_shadow_simple.h \
#    ../../../source/graphics/render/gl_render/vs_per_vertex_lighting_diffuse_specular.h \
#    ../../../source/graphics/render/gl_render/vs_per_vertex_lighting_tex_diffuse.h \
#    ../../../source/graphics/render/gl_render/vs_pfl_diffuse_simple_shadow.h \
#    ../../../source/graphics/render/gl_render/vs_skinning_bump.h \
#    ../../../source/graphics/render/gl_render/vs_skinning_depth.h \
#    ../../../source/graphics/render/gl_render/vs_solid_vertex_color.h \
#    ../../../source/graphics/render/gl_render/vs_terrain.h \
#    ../../../source/graphics/render/gl_render/vs_transform_3d.h \
#    ../../../source/graphics/render/gl_render/vs_transformed_textured_3d.h \
    ../../../source/graphics/render/irender.h \
    ../../../source/graphics/render/irender_context.h \
    ../../../source/graphics/render/irender_context_factory.h \
    ../../../source/graphics/render/irender_queue.h \
    ../../../source/graphics/render/ishader.h \
    ../../../source/graphics/render/module.h \
    ../../../source/graphics/render/render_batch.h \
    ../../../source/graphics/render/render_context_select.h \
    ../../../source/graphics/render/render_context_type.h \
    ../../../source/graphics/render/render_pass.h \
    ../../../source/graphics/render/shader_type.h \
    ../../../source/graphics/renderable/gl_renderable/gl_renderable_builder.h \
    ../../../source/graphics/renderable/gl_renderable/module.h \
    ../../../source/graphics/renderable/old/cube_mesh.h \
    ../../../source/graphics/renderable/old/grid_object.h \
    ../../../source/graphics/renderable/old/lines.h \
    ../../../source/graphics/renderable/old/points.h \
    ../../../source/graphics/renderable/old/primitive_types.h \
    ../../../source/graphics/renderable/old/quad_mesh.h \
    ../../../source/graphics/renderable/old/scaled_grid.h \
    ../../../source/graphics/renderable/old/skin_mesh.h \
    ../../../source/graphics/renderable/old/sphere_mesh.h \
    ../../../source/graphics/renderable/old/static_mesh.h \
    ../../../source/graphics/renderable/old/triangle_fans.h \
    ../../../source/graphics/renderable/old/triangle_strip.h \
    ../../../source/graphics/renderable/old/triangles.h \
    ../../../source/graphics/renderable/irenderable_builder.h \
    ../../../source/graphics/renderable/module.h \
    ../../../source/graphics/renderable/renderable_builder.h \
    ../../../source/graphics/shaders/module.h \
    ../../../source/graphics/shaders/shader_attribute.h \
    ../../../source/graphics/shaders/shader_builder.h \
    ../../../source/graphics/shaders/shader_data_type.h \
    ../../../source/graphics/shaders/shader_function.h \
    ../../../source/graphics/shaders/shader_type.h \
    ../../../source/graphics/shaders/shader_uniform_variable.h \
    ../../../source/graphics/shaders/shader_var_table.h \
    ../../../source/graphics/shaders/shader_variable.h \
    ../../../source/graphics/shadow/abstract_shadow_map_debug_visualizer.h \
    ../../../source/graphics/shadow/abstract_shadowmap_render.h \
    ../../../source/graphics/shadow/cascade_shadow_map_debug_visualizer.h \
    ../../../source/graphics/shadow/cascade_shadow_map_render.h \
    ../../../source/graphics/shadow/shadow_map_render_type.h \
    ../../../source/graphics/shadow/shadow_model.h \
    ../../../source/graphics/shadow/shadow_render_common.h \
    #../../../source/graphics/shadow/simple_shadowmap_render.h \
    ../../../source/graphics/state/gpu_state.h \
    ../../../source/graphics/state/module.h \
    ../../../source/graphics/text/itext_surface.h \
    ../../../source/graphics/text/module.h \
    ../../../source/graphics/text/text_direction.h \
    ../../../source/graphics/text/text_horizontal_alignment.h \
    ../../../source/graphics/text/text_surface.h \
    ../../../source/graphics/text/text_vertical_alignment.h \
    ../../../source/graphics/texture/gl_texture/gl_texture2d.h \
    ../../../source/graphics/texture/gl_texture/gl_texture2d_array.h \
    ../../../source/graphics/texture/gl_texture/gl_texture_convert.h \
    ../../../source/graphics/texture/gl_texture/module.h \
    ../../../source/graphics/texture/itexture.h \
    ../../../source/graphics/texture/itexture2d.h \
    ../../../source/graphics/texture/itexture2d_array.h \
    ../../../source/graphics/texture/module.h \
    ../../../source/graphics/texture/texture_compare_func.h \
    ../../../source/graphics/texture/texture_compare_mode.h \
    ../../../source/graphics/texture/texture_context.h \
    ../../../source/graphics/texture/texture_filter.h \
    ../../../source/graphics/texture/texture_wrap.h \
    ../../../source/graphics/video_driver/gl_video_driver/gl_capabilities.h \
    ../../../source/graphics/video_driver/gl_video_driver/gl_settings.h \
    ../../../source/graphics/video_driver/gl_video_driver/gl_vfs.h \
    ../../../source/graphics/video_driver/gl_video_driver/gl_video_driver.h \
    ../../../source/graphics/video_driver/gl_video_driver/module.h \
    ../../../source/graphics/video_driver/gpu_config.h \
    ../../../source/graphics/video_driver/ivideo_driver.h \
    ../../../source/graphics/video_driver/ivideo_driver_settings.h \
    ../../../source/graphics/video_driver/module.h \
    ../../../source/graphics/video_driver/video_driver.h \
    ../../../source/graphics/video_driver/video_driver_creator.h \
    ../../../source/graphics/video_driver/video_driver_type.h \
    ../../../source/graphics/video_memory/gl_video_memory/ati_meminfo.h \
    ../../../source/graphics/video_memory/gl_video_memory/module.h \
    ../../../source/graphics/video_memory/gl_video_memory/nvx_gpu_memory_info.h \
    ../../../source/graphics/video_memory/gl_video_memory/video_memory.h \
    ../../../source/graphics/video_memory/ivideo_memory.h \
    ../../../source/graphics/video_memory/module.h \
    ../../../source/graphics/config.h \
    ../../../source/graphics/module.h

SOURCES += \
    ../../../source/graphics/attributes/gpu_opengl_module.cpp \
    ../../../source/graphics/attributes/module.cpp \
    ../../../source/graphics/blending/blend_function.cpp \
    ../../../source/graphics/blending/gl_blending.cpp \
    ../../../source/graphics/buffers/ibo.cpp \
    ../../../source/graphics/buffers/pbo.cpp \
    ../../../source/graphics/buffers/vbo.cpp \
    ../../../source/graphics/canvas/canvas.cpp \
    ../../../source/graphics/canvas/canvas_desciption.cpp \
    ../../../source/graphics/error/graphics_error.cpp \
    ../../../source/graphics/fog/fog.cpp \
    ../../../source/graphics/fog/fog_mode.cpp \
    ../../../source/graphics/frame/frame.cpp \
    ../../../source/graphics/frame_buffer/gl_frame_buffer/gl_color_render_buffer.cpp \
    ../../../source/graphics/frame_buffer/gl_frame_buffer/gl_depth_render_buffer.cpp \
    ../../../source/graphics/frame_buffer/gl_frame_buffer/gl_frame_buffer.cpp \
    ../../../source/graphics/frame_buffer/gl_frame_buffer/gl_frame_buffer_config.cpp \
    ../../../source/graphics/frame_buffer/gl_frame_buffer/gl_frame_buffer_convert.cpp \
    ../../../source/graphics/frame_buffer/gl_frame_buffer/gl_query_supprted_frame_buffer_configs.cpp \
    ../../../source/graphics/frame_buffer/color_render_buffer.cpp \
    ../../../source/graphics/frame_buffer/depth_render_buffer.cpp \
    ../../../source/graphics/frame_buffer/frame_buffer.cpp \
    ../../../source/graphics/frame_buffer/frame_buffer_config.cpp \
    ../../../source/graphics/frame_buffer/frame_buffer_target.cpp \
    ../../../source/graphics/frame_buffer/render_buffer.cpp \
    ../../../source/graphics/frame_buffer/render_buffer_config.cpp \
    ../../../source/graphics/lighting/light_model.cpp \
    ../../../source/graphics/lighting/light_parameters.cpp \
    ../../../source/graphics/material/gpu_material.cpp \
    ../../../source/graphics/nvtristrip/nv_tri_strip.cpp \
    ../../../source/graphics/nvtristrip/nv_tri_strip_objects.cpp \
    ../../../source/graphics/nvtristrip/vertex_cache.cpp \
    ../../../source/graphics/opengl/error/gl_error_check.cpp \
    ../../../source/graphics/opengl/extensions.cpp \
    ../../../source/graphics/painter/gl_painter/gl_paint_engine.cpp \
    ../../../source/graphics/painter/brush.cpp \
    ../../../source/graphics/painter/paint_device.cpp \
    ../../../source/graphics/painter/paint_engine.cpp \
    ../../../source/graphics/painter/painter.cpp \
    ../../../source/graphics/painter/pen.cpp \
    ../../../source/graphics/primitives/gl_primitive/gl_attribute_configer.cpp \
    ../../../source/graphics/primitives/gl_primitive/gl_primitive_type.cpp \
    ../../../source/graphics/primitives/gl_primitive/gl_renderable.cpp \
    ../../../source/graphics/primitives/cube_mesh.cpp \
    ../../../source/graphics/primitives/frustum_mesh.cpp \
    ../../../source/graphics/primitives/grid_object.cpp \
    ../../../source/graphics/primitives/lines.cpp \
    ../../../source/graphics/primitives/points.cpp \
    ../../../source/graphics/primitives/primitive_type.cpp \
    ../../../source/graphics/primitives/quad_mesh.cpp \
    ../../../source/graphics/primitives/renderable.cpp \
    ../../../source/graphics/primitives/scaled_grid.cpp \
    ../../../source/graphics/primitives/skin_mesh.cpp \
    ../../../source/graphics/primitives/sphere_mesh.cpp \
    ../../../source/graphics/primitives/static_mesh.cpp \
    ../../../source/graphics/primitives/triangle_fans.cpp \
    ../../../source/graphics/primitives/triangle_strip.cpp \
    ../../../source/graphics/primitives/triangles.cpp \
#    ../../../source/graphics/render/gl_render/fs_bump.cpp \
#    ../../../source/graphics/render/gl_render/fs_bump_diffuse_color.cpp \
#    ../../../source/graphics/render/gl_render/fs_bump_diffuse_color_specular.cpp \
#    ../../../source/graphics/render/gl_render/fs_bump_shadow_map.cpp \
#    ../../../source/graphics/render/gl_render/fs_bump_tex_diffuse.cpp \
#    ../../../source/graphics/render/gl_render/fs_bump_tex_diffuse_specular.cpp \
#    ../../../source/graphics/render/gl_render/fs_depth.cpp \
#    ../../../source/graphics/render/gl_render/fs_grass.cpp \
#    ../../../source/graphics/render/gl_render/fs_gui.cpp \
#    ../../../source/graphics/render/gl_render/fs_light.cpp \
#    ../../../source/graphics/render/gl_render/fs_painter.cpp \
#    ../../../source/graphics/render/gl_render/fs_particle.cpp \
#    ../../../source/graphics/render/gl_render/fs_per_fragment_lighting_diffuse.cpp \
#    ../../../source/graphics/render/gl_render/fs_per_fragment_lighting_diffuse_specular.cpp \
#    ../../../source/graphics/render/gl_render/fs_per_fragment_lighting_tex_diffuse.cpp \
#    ../../../source/graphics/render/gl_render/fs_per_fragment_lighting_tex_diffuse_specular.cpp \
#    ../../../source/graphics/render/gl_render/fs_per_vertex_lighting_diffuse.cpp \
#    ../../../source/graphics/render/gl_render/fs_per_vertex_lighting_diffuse_shadow_simple.cpp \
#    ../../../source/graphics/render/gl_render/fs_per_vertex_lighting_tex_diffuse.cpp \
#    ../../../source/graphics/render/gl_render/fs_pfl_diffuse_simple_shadow.cpp \
#    ../../../source/graphics/render/gl_render/fs_shadow_single.cpp \
#    ../../../source/graphics/render/gl_render/fs_skinning.cpp \
#    ../../../source/graphics/render/gl_render/fs_solid_textured.cpp \
#    ../../../source/graphics/render/gl_render/fs_solid_textured_2d_array.cpp \
#    ../../../source/graphics/render/gl_render/fs_solid_vertex_color.cpp \
#    ../../../source/graphics/render/gl_render/fs_terrain.cpp \
#    ../../../source/graphics/render/gl_render/fs_text_solid.cpp \
    ../../../source/graphics/render/gl_render/gl_rc_dynamic.cpp \
    ../../../source/graphics/render/gl_render/gl_rc_instances.cpp \
    ../../../source/graphics/render/gl_render/gl_render_context_base.cpp \
    ../../../source/graphics/render/gl_render/gl_render_context_factory.cpp \
    ../../../source/graphics/render/gl_render/gl_shader_base.cpp \
    ../../../source/graphics/render/gl_render/gl_shader_cooker.cpp \
    ../../../source/graphics/render/gl_render/gl_shader_type.cpp \
#    ../../../source/graphics/render/gl_render/vs_bump.cpp \
#    ../../../source/graphics/render/gl_render/vs_bump_diffuse_color.cpp \
#    ../../../source/graphics/render/gl_render/vs_bump_diffuse_color_specular.cpp \
#    ../../../source/graphics/render/gl_render/vs_bump_shadow_map.cpp \
#    ../../../source/graphics/render/gl_render/vs_bump_tex_diffuse.cpp \
#    ../../../source/graphics/render/gl_render/vs_bump_tex_diffuse_specular.cpp \
#    ../../../source/graphics/render/gl_render/vs_depth.cpp \
#    ../../../source/graphics/render/gl_render/vs_grass.cpp \
#    ../../../source/graphics/render/gl_render/vs_gui.cpp \
#    ../../../source/graphics/render/gl_render/vs_light.cpp \
#    ../../../source/graphics/render/gl_render/vs_painter.cpp \
#    ../../../source/graphics/render/gl_render/vs_particle.cpp \
#    ../../../source/graphics/render/gl_render/vs_particle_system.cpp \
#    ../../../source/graphics/render/gl_render/vs_per_fragment_lighting_diffuse.cpp \
#    ../../../source/graphics/render/gl_render/vs_per_fragment_lighting_diffuse_specular.cpp \
#    ../../../source/graphics/render/gl_render/vs_per_fragment_lighting_tex_diffuse.cpp \
#    ../../../source/graphics/render/gl_render/vs_per_fragment_lighting_tex_diffuse_specular.cpp \
#    ../../../source/graphics/render/gl_render/vs_per_vertex_lighting.cpp \
#    ../../../source/graphics/render/gl_render/vs_per_vertex_lighting_diffuse.cpp \
#    ../../../source/graphics/render/gl_render/vs_per_vertex_lighting_diffuse_shadow_simple.cpp \
#    ../../../source/graphics/render/gl_render/vs_per_vertex_lighting_diffuse_specular.cpp \
#    ../../../source/graphics/render/gl_render/vs_per_vertex_lighting_tex_diffuse.cpp \
#    ../../../source/graphics/render/gl_render/vs_pfl_diffuse_simple_shadow.cpp \
#    ../../../source/graphics/render/gl_render/vs_skinning_bump.cpp \
#    ../../../source/graphics/render/gl_render/vs_skinning_depth.cpp \
#    ../../../source/graphics/render/gl_render/vs_solid_vertex_color.cpp \
#    ../../../source/graphics/render/gl_render/vs_terrain.cpp \
#    ../../../source/graphics/render/gl_render/vs_transform_3d.cpp \
#    ../../../source/graphics/render/gl_render/vs_transformed_textured_3d.cpp \
    ../../../source/graphics/render/irender.cpp \
    ../../../source/graphics/render/irender_context.cpp \
    ../../../source/graphics/render/irender_queue.cpp \
    ../../../source/graphics/render/render_batch.cpp \
    ../../../source/graphics/render/render_context_select.cpp \
    ../../../source/graphics/render/render_context_type.cpp \
    ../../../source/graphics/render/render_pass.cpp \
    ../../../source/graphics/renderable/gl_renderable/gl_renderable_builder.cpp \
    ../../../source/graphics/renderable/old/cube_mesh.cpp \
    ../../../source/graphics/renderable/old/grid_object.cpp \
    ../../../source/graphics/renderable/old/lines.cpp \
    ../../../source/graphics/renderable/old/points.cpp \
    ../../../source/graphics/renderable/old/quad_mesh.cpp \
    ../../../source/graphics/renderable/old/scaled_grid.cpp \
    ../../../source/graphics/renderable/old/skin_mesh.cpp \
    ../../../source/graphics/renderable/old/sphere_mesh.cpp \
    ../../../source/graphics/renderable/old/static_mesh.cpp \
    ../../../source/graphics/renderable/old/triangles.cpp \
    ../../../source/graphics/renderable/old/vertex_array_object.cpp \
    ../../../source/graphics/renderable/renderable_builder.cpp \
    ../../../source/graphics/shaders/shader_builder.cpp \
    ../../../source/graphics/shaders/shader_function.cpp \
    ../../../source/graphics/shaders/shader_uniform_table.cpp \
    ../../../source/graphics/shaders/shader_var_table.cpp \
#    ../../../source/graphics/shadow/abstract_shadow_map_debug_visualizer.cpp \
#    ../../../source/graphics/shadow/abstract_shadowmap_render.cpp \
#    ../../../source/graphics/shadow/cascade_shadow_map_debug_visualizer.cpp \
#    ../../../source/graphics/shadow/cascade_shadow_map_render.cpp \
#    ../../../source/graphics/shadow/shadow_map_render_type.cpp \
#    ../../../source/graphics/shadow/shadow_model.cpp \
#    ../../../source/graphics/shadow/shadow_render_common.cpp \
    #../../../source/graphics/shadow/simple_shadowmap_render.cpp \
    ../../../source/graphics/state/gpu_state.cpp \
    ../../../source/graphics/text/text_surface.cpp \
    ../../../source/graphics/texture/gl_texture/gl_texture2d.cpp \
    ../../../source/graphics/texture/gl_texture/gl_texture2d_array.cpp \
    ../../../source/graphics/texture/gl_texture/gl_texture_convert.cpp \
    ../../../source/graphics/texture/texture_context.cpp \
    ../../../source/graphics/video_driver/gl_video_driver/gl_capabilities.cpp \
    ../../../source/graphics/video_driver/gl_video_driver/gl_settings.cpp \
    ../../../source/graphics/video_driver/gl_video_driver/gl_vfs.cpp \
    ../../../source/graphics/video_driver/gl_video_driver/gl_video_driver.cpp \
    ../../../source/graphics/video_driver/video_driver.cpp \
    ../../../source/graphics/video_driver/video_driver_creator.cpp \
    ../../../source/graphics/video_memory/gl_video_memory/video_memory.cpp \
    ../../../source/graphics/gpu_common_module.cpp \
    ../../../source/graphics/gpu_module.cpp

