######################################################################
# Automatically generated by qmake (2.01a) ?? 25. ??? 19:53:26 2013
######################################################################

include(../punk_common.pri)

CONFIG += dll
TEMPLATE = lib
TARGET = punk_attributes

LIBS += -L$${LIBDIR} -lpunk_error -lpunk_string -lpunk_core -lpunk_math -lpunk_system -lpunk_graphics -lpunk_image

INCLUDEPATH += ../../../source

HEADERS += \
    ../../../source/attributes/building.h \
    ../../../source/attributes/interface.h \
    ../../../source/attributes/intersection.h \
    ../../../source/attributes/module.h \
    ../../../source/attributes/scheme.h \
    ../../../source/attributes/sound.h \
    ../../../source/attributes/track_pos.h \
    ../../../source/attributes/animation/action.h \
    ../../../source/attributes/animation/action_male_walk.h \
    ../../../source/attributes/animation/animation.h \
    ../../../source/attributes/animation/animation_mixer.h \
    ../../../source/attributes/animation/animation_track.h \
    ../../../source/attributes/animation/armature_animation_mixer.h \
    ../../../source/attributes/animation/bone_animation.h \
    ../../../source/attributes/animation/interface.h \
    ../../../source/attributes/animation/module.h \
    ../../../source/attributes/animation/object_animation.h \
    ../../../source/attributes/animation/object_animation_mixer.h \
    ../../../source/attributes/controllers/camera_controller.h \
    ../../../source/attributes/controllers/controllers.h \
    ../../../source/attributes/data/camera.h \
    ../../../source/attributes/data/door.h \
    ../../../source/attributes/data/entity.h \
    ../../../source/attributes/data/geometry.h \
    ../../../source/attributes/data/interface.h \
    ../../../source/attributes/data/interior_location.h \
    ../../../source/attributes/data/light.h \
    ../../../source/attributes/data/light_set.h \
    ../../../source/attributes/data/location.h \
    ../../../source/attributes/data/material.h \
    ../../../source/attributes/data/material_manager.h \
    ../../../source/attributes/data/module.h \
    ../../../source/attributes/data/old_shape_mesh.h \
    ../../../source/attributes/data/proxy.h \
    ../../../source/attributes/data/skin_geometry.h \
    ../../../source/attributes/data/static_geometry.h \
    ../../../source/attributes/data/texture_slot.h \
    ../../../source/attributes/data/transform.h \
    ../../../source/attributes/data/world.h \
    ../../../source/attributes/data/lights/directional_light.h \
    ../../../source/attributes/data/lights/point_light.h \
    ../../../source/attributes/data/lights/spot_light.h \
    ../../../source/attributes/data/lights/sun.h \
    ../../../source/attributes/manager/camera_manager.h \
    ../../../source/attributes/manager/manager.h \
    ../../../source/attributes/manager/material_manager.h \
    ../../../source/attributes/motions/key_based_strategy.h \
    ../../../source/attributes/motions/motion.h \
    ../../../source/attributes/motions/motion_strategy.h \
    ../../../source/attributes/motions/static_motion_strategy.h \
    ../../../source/attributes/objects/module.h \
    ../../../source/attributes/objects/simple/module.h \
    ../../../source/attributes/objects/simple/solid_cube.h \
    ../../../source/attributes/objects/characters/human.h \
    ../../../source/attributes/objects/characters/human_impl.h \
    ../../../source/attributes/objects/characters/male_human.h \
    ../../../source/attributes/objects/characters/male_human_impl.h \
    ../../../source/attributes/skinning/armature.h \
    ../../../source/attributes/skinning/bone.h \
    ../../../source/attributes/skinning/bone_frame.h \
    ../../../source/attributes/skinning/human_armature.h \
    ../../../source/attributes/skinning/human_female_armature.h \
    ../../../source/attributes/skinning/human_male_armature.h \
    ../../../source/attributes/skinning/interface.h \
    ../../../source/attributes/skinning/module.h \
    ../../../source/attributes/skinning/types.h \
    ../../../source/attributes/terrain/interface.h \
    ../../../source/attributes/terrain/module.h \
    ../../../source/attributes/terrain/terrain.h \
    ../../../source/attributes/terrain/terrain_cell.h \
    ../../../source/attributes/terrain/terrain_data.h \
    ../../../source/attributes/terrain/terrain_loader.h \
    ../../../source/attributes/terrain/terrain_manager.h \
    ../../../source/attributes/terrain/terrain_mesh.h \
    ../../../source/attributes/terrain/terrain_observer.h \
    ../../../source/attributes/terrain/terrain_processor.h \
    ../../../source/attributes/terrain/terrain_streamer.h \
    ../../../source/attributes/terrain/terrain_view.h \
    ../../../source/attributes/terrain/terrain_view_loader.h \
    ../../../source/attributes/terrain/terrain_view_processor.h \
    ../../../source/attributes/water/interface.h \
    ../../../source/attributes/water/module.h \
    ../../../source/attributes/water/river.h

SOURCES += \
    ../../../source/attributes/building.cpp \
    ../../../source/attributes/scheme.cpp \
    ../../../source/attributes/sound.cpp \
    ../../../source/attributes/animation/action.cpp \
    ../../../source/attributes/animation/action_male_walk.cpp \
    ../../../source/attributes/animation/animation.cpp \
    ../../../source/attributes/animation/animation_mixer.cpp \
    ../../../source/attributes/animation/animation_track.cpp \
    ../../../source/attributes/animation/armature_animation_mixer.cpp \
    ../../../source/attributes/animation/bone_animation.cpp \
    ../../../source/attributes/animation/object_animation.cpp \
    ../../../source/attributes/animation/object_animation_mixer.cpp \
    ../../../source/attributes/controllers/camera_controller.cpp \
    ../../../source/attributes/data/camera.cpp \
    ../../../source/attributes/data/entity.cpp \
    ../../../source/attributes/data/geometry.cpp \
    ../../../source/attributes/data/light.cpp \
    ../../../source/attributes/data/light_set.cpp \
    ../../../source/attributes/data/material.cpp \
    ../../../source/attributes/data/proxy.cpp \
    ../../../source/attributes/data/skin_geometry.cpp \
    ../../../source/attributes/data/static_geometry.cpp \
    ../../../source/attributes/data/texture_slot.cpp \
    ../../../source/attributes/data/transform.cpp \
    ../../../source/attributes/data/world.cpp \
    ../../../source/attributes/data/lights/directional_light.cpp \
    ../../../source/attributes/data/lights/point_light.cpp \
    ../../../source/attributes/data/lights/spot_light.cpp \
    ../../../source/attributes/data/lights/sun.cpp \
    ../../../source/attributes/manager/camera_manager.cpp \
    ../../../source/attributes/manager/material_manager.cpp \
    ../../../source/attributes/motions/motion_strategy.cpp \
    ../../../source/attributes/motions/static_motion_strategy.cpp \
    ../../../source/attributes/objects/simple/solid_cube.cpp \
    ../../../source/attributes/objects/characters/human.cpp \
    ../../../source/attributes/objects/characters/male_human.cpp \
    ../../../source/attributes/skinning/armature.cpp \
    ../../../source/attributes/skinning/bone.cpp \
    ../../../source/attributes/skinning/human_armature.cpp \
    ../../../source/attributes/skinning/human_female_armature.cpp \
    ../../../source/attributes/skinning/human_male_armature.cpp \
    ../../../source/attributes/terrain/terrain.cpp \
    ../../../source/attributes/terrain/terrain_cell.cpp \
    ../../../source/attributes/terrain/terrain_data.cpp \
    ../../../source/attributes/terrain/terrain_loader.cpp \
    ../../../source/attributes/terrain/terrain_manager.cpp \
    ../../../source/attributes/terrain/terrain_mesh.cpp \
    ../../../source/attributes/terrain/terrain_observer.cpp \
    ../../../source/attributes/terrain/terrain_processor.cpp \
    ../../../source/attributes/terrain/terrain_streamer.cpp \
    ../../../source/attributes/terrain/terrain_view.cpp \
    ../../../source/attributes/terrain/terrain_view_loader.cpp \
    ../../../source/attributes/terrain/terrain_view_processor.cpp \
    ../../../source/attributes/water/river.cpp
