######################################################################
# Automatically generated by qmake (2.01a) ?? 25. ??? 19:53:26 2013
######################################################################

include(../punk_common.pri)

CONFIG += dll
TEMPLATE = lib
TARGET = punk_attributes

LIBS += -L$${LIBDIR} -lpunk_error -lpunk_string -lpunk_core -lpunk_math -lpunk_system -lpunk_graphics -lpunk_image

INCLUDEPATH += ../../../source

HEADERS += \
    ../../../source/attributes/animation/ianimated.h \
    ../../../source/attributes/animation/ianimation.h \
    ../../../source/attributes/animation/ianimation_player.h \
    ../../../source/attributes/animation/ianimation_pool.h \
    ../../../source/attributes/animation/ikeyframe.h \
    ../../../source/attributes/animation/ikeyframe_interpolator.h \
    ../../../source/attributes/animation/itrack.h \
    ../../../source/attributes/animation/module.h \
    ../../../source/attributes/camera/icamera.h \
    ../../../source/attributes/camera/iperspective_camera.h \
    ../../../source/attributes/camera/module.h \
    ../../../source/attributes/geometry/geometry.h \
    ../../../source/attributes/geometry/geometry_cooker.h \
    ../../../source/attributes/geometry/icomponent_bone_weight.h \
    ../../../source/attributes/geometry/icomponent_color.h \
    ../../../source/attributes/geometry/icomponent_index.h \
    ../../../source/attributes/geometry/icomponent_normal.h \
    ../../../source/attributes/geometry/icomponent_position.h \
    ../../../source/attributes/geometry/icomponent_texture.h \
    ../../../source/attributes/geometry/icomponent_texture_face.h \
    ../../../source/attributes/geometry/igeometry.h \
    ../../../source/attributes/geometry/igeometry_cooker.h \
    ../../../source/attributes/geometry/module.h \
    ../../../source/attributes/light/idirectional_light.h \
    ../../../source/attributes/light/ilight.h \
    ../../../source/attributes/light/ipoint_light.h \
    ../../../source/attributes/light/ispot_light.h \
    ../../../source/attributes/light/light_set.h \
    ../../../source/attributes/light/module.h \
    ../../../source/attributes/material/idiffuse_texture_slot.h \
    ../../../source/attributes/material/imaterial.h \
    ../../../source/attributes/material/inormal_texture_slot.h \
    ../../../source/attributes/material/ispecular_intensity_texture_slot.h \
    ../../../source/attributes/material/itexture_slot.h \
    ../../../source/attributes/material/material.h \
    ../../../source/attributes/material/material_manager.h \
    ../../../source/attributes/material/module.h \
    ../../../source/attributes/material/texture_slot.h \
    ../../../source/attributes/skinning/iarmature.h \
    ../../../source/attributes/skinning/iarmature_schema.h \
    ../../../source/attributes/skinning/ibone.h \
    ../../../source/attributes/skinning/interface.h \
    ../../../source/attributes/skinning/module.h \
    ../../../source/attributes/stubs/file_stub.h \
    ../../../source/attributes/stubs/ifile_stub.h \
    ../../../source/attributes/stubs/itext_attribute.h \
    ../../../source/attributes/stubs/module.h \
    ../../../source/attributes/stubs/text_attribute.h \
    ../../../source/attributes/transform/itransform.h \
    ../../../source/attributes/transform/module.h \
    ../../../source/attributes/transform/transform.h

SOURCES += \
    ../../../source/attributes/animation/ianimation.cpp \
    ../../../source/attributes/animation/ianimation_player.cpp \
    ../../../source/attributes/animation/ianimation_pool.cpp \
    ../../../source/attributes/animation/ikeyframe.cpp \
    ../../../source/attributes/animation/ikeyframe_interpolator.cpp \
    ../../../source/attributes/animation/itrack.cpp \
    ../../../source/attributes/camera/camera.cpp \
    ../../../source/attributes/geometry/geometry.cpp \
    ../../../source/attributes/geometry/geometry_cooker.cpp \
    ../../../source/attributes/light/light.cpp \
    ../../../source/attributes/light/light_set.cpp \
    ../../../source/attributes/material/material.cpp \
    ../../../source/attributes/material/texture_slot.cpp \
    ../../../source/attributes/skinning/iarmature.cpp \
    ../../../source/attributes/skinning/iarmature_schema.cpp \
    ../../../source/attributes/skinning/ibone.cpp \
    ../../../source/attributes/stubs/ifile_stub.cpp \
    ../../../source/attributes/stubs/text_attribute.cpp \
    ../../../source/attributes/transform/transform.cpp

