######################################################################
# Automatically generated by qmake (2.01a) ?? 25. ??? 19:53:26 2013
######################################################################

include(../punk_common.pri)

CONFIG += dll
TEMPLATE = lib
TARGET = punk_system

LIBS += -lX11

LIBS += -L$${LIBDIR} -lpunk_error -lpunk_string -lpunk_core

INCLUDEPATH += ../../../source

HEADERS += \
    ../../../source/system/window/module.h \
    ../../../source/system/window/win32_window.h \
    ../../../source/system/window/window_adapter.h \
    ../../../source/system/window/window_component.h \
    ../../../source/system/window/window_description.h \
    ../../../source/system/window/window_interface.h \
    ../../../source/system/window/window.h \
    ../../../source/system/window/x11_window.h \
    ../../../source/system/errors/assert2.h \
    ../../../source/system/errors/error.h \
    ../../../source/system/errors/exceptions.h \
    ../../../source/system/errors/module.h \
    ../../../source/system/errors/stack_trace.h \
    ../../../source/system/events/event_type.h \
    ../../../source/system/events/event.h \
    ../../../source/system/events/idle_event.h \
    ../../../source/system/events/interface.h \
    ../../../source/system/events/key_event.h \
    ../../../source/system/events/model_time_step_event.h \
    ../../../source/system/events/module.h \
    ../../../source/system/events/mouse_event.h \
    ../../../source/system/events/mouse_hoover_event.h \
    ../../../source/system/events/mouse_wheel_event.h \
    ../../../source/system/events/window_resize_event.h \
    ../../../source/system/input/camera_capture.h \
    ../../../source/system/input/console.h \
    ../../../source/system/input/input_component.h \
    ../../../source/system/input/keyboard_interface.h \
    ../../../source/system/input/keyboard.h \
    ../../../source/system/input/keymap_interface.h \
    ../../../source/system/input/keymap.h \
    ../../../source/system/input/module.h \
    ../../../source/system/input/mouse_interface.h \
    ../../../source/system/input/mouse.h \
    ../../../source/system/time/clock_interface.h \
    ../../../source/system/time/clock.h \
    ../../../source/system/time/module.h \
    ../../../source/system/time/time_component.h \
    ../../../source/system/time/timer_interface.h \
    ../../../source/system/time/timer.h \
    ../../../source/system/logger/console_logger.h \
    ../../../source/system/logger/error_logger.h \
    ../../../source/system/logger/file_logger.h \
    ../../../source/system/logger/logger_component.h \
    ../../../source/system/logger/logger_interface.h \
    ../../../source/system/logger/logger.h \
    ../../../source/system/logger/message_logger.h \
    ../../../source/system/logger/module.h \
    ../../../source/system/logger/warning_logger.h

SOURCES += \
    ../../../source/system/window/win32_window.cpp \
    ../../../source/system/window/window_component.cpp \
    ../../../source/system/window/window.cpp \
    ../../../source/system/window/x11_window.cpp \
    ../../../source/system/errors/assert2.cpp \
    ../../../source/system/errors/error.cpp \
    ../../../source/system/errors/exceptions.cpp \
    ../../../source/system/errors/stack_trace.cpp \
    ../../../source/system/events/idle_event.cpp \
    ../../../source/system/events/key_event.cpp \
    ../../../source/system/events/model_time_step_event.cpp \
    ../../../source/system/events/mouse_event.cpp \
    ../../../source/system/events/mouse_hoover_event.cpp \
    ../../../source/system/events/mouse_wheel_event.cpp \
    ../../../source/system/events/window_resize_event.cpp \
    ../../../source/system/input/camera_capture.cpp \
    ../../../source/system/input/console.cpp \
    ../../../source/system/input/input_component.cpp \
    ../../../source/system/input/keyboard.cpp \
    ../../../source/system/input/keymap.cpp \
    ../../../source/system/input/mouse.cpp \
    ../../../source/system/time/clock.cpp \
    ../../../source/system/time/time_component.cpp \
    ../../../source/system/time/timer.cpp \
    ../../../source/system/logger/console_logger.cpp \
    ../../../source/system/logger/error_logger.cpp \
    ../../../source/system/logger/file_logger.cpp \
    ../../../source/system/logger/logger_component.cpp \
    ../../../source/system/logger/logger.cpp \
    ../../../source/system/logger/message_logger.cpp \
    ../../../source/system/logger/warning_logger.cpp
