######################################################################
# Automatically generated by qmake (2.01a) ?? 25. ??? 19:53:26 2013
######################################################################

TEMPLATE = subdirs
CONFIG += ordered
CONFIG -= QT

SUBDIRS = punk_samples/punk_native_window
