#ifndef __attribute_panel_impl__
#define __attribute_panel_impl__

/**
@file
Subclass of AttributePanel, which is generated by wxFormBuilder.
*/

#include "forms.h"
#include <tools/editor/editor_interface.h>

//// end generated include

PUNK_ENGINE_BEGIN
namespace Tools {
	/** Implementing AttributePanel */
	class AttributePanelImpl : public AttributePanel, public IEditorParametersPanel
	{
	public:
		/** Constructor */
		AttributePanelImpl(wxWindow* parent);
		//// end generated class members
		//	IObject
		void QueryInterface(const Core::Guid& type, void** object) override;
		std::uint32_t AddRef() override;
		std::uint32_t Release() override;

		//	IEditorParametersPanel
		void AddIntegerEditor(const Core::String& name, int* value) override;
		void AddBooleanEditor(const Core::String& name, bool *value) override;
		void AddFloatEditor(const Core::String& name, float* value) override;
		void AddDoubleEditor(const Core::String& name, double* value) override;
		void AddStringEditor(const Core::String& name, Core::String* value) override;
		void AddVec4FloatEditor(const Core::String& name, Math::vec4* value) override;
		void AddVec3FloatEditor(const Core::String& name, Math::vec3* value) override;
		void AddVec2FloatEditor(const Core::String& name, Math::vec2* value) override;
		void AddQuatFloatEditor(const Core::String& name, Math::quat* value) override;
		void AddMat4FloatEditor(const Core::String& name, Math::mat4* value) override;
		void AddMat3FloatEditor(const Core::String& name, Math::mat3* value) override;
		void AddMat2FloatEditor(const Core::String& name, Math::mat2* value) override;
	};
}
PUNK_ENGINE_END

#endif // __attribute_panel_impl__
