#ifndef __attribute_dialog_impl__
#define __attribute_dialog_impl__

/**
@file
Subclass of AttributeDialog, which is generated by wxFormBuilder.
*/

#include <config.h>
#include "forms.h"
#include "attribute_panel_impl.h"
#include <scene/module.h>

//// end generated include

PUNK_ENGINE_BEGIN
namespace Tools {
	/** Implementing AttributeDialog */
	class AttributeDialogImpl : public AttributeDialog
	{
	protected:
		// Handlers for AttributeDialog events.
		void OnOk(wxCommandEvent& event);
		void OnCancel(wxCommandEvent& event);
		void OnGroupSelected(wxCommandEvent& event);
		void OnItemChanged(wxCommandEvent& event);
	public:
		/** Constructor */
		AttributeDialogImpl(wxWindow* parent);
		
		//// end generated class members
		
		Core::Pointer<Core::IObject> GetObject() {
			return m_object;
		}

		void SetObject(Core::Pointer<Core::IObject> attribute);
		
		void SetObjectName(const Core::String& value);
		
		const Core::String& GetObjectName() const {
			return m_name;
		}

		Core::Pointer<Core::IObject> CreateObject();
		void UpdatePanel();
	
	private:
		AttributePanelImpl* m_attributes_panel;
		Core::Pointer<Core::IObject> m_object;
		Core::String m_name;
	};
}

PUNK_ENGINE_END

#endif // __attribute_dialog_impl__
