#ifndef __attribute_dialog_impl__
#define __attribute_dialog_impl__

/**
@file
Subclass of AttributeDialog, which is generated by wxFormBuilder.
*/

#include <config.h>
#include "forms.h"
#include "attribute_panel_impl.h"
#include <scene/module.h>

//// end generated include

PUNK_ENGINE_BEGIN
namespace Tools {
	/** Implementing AttributeDialog */
	class AttributeDialogImpl : public AttributeDialog
	{
	protected:
		// Handlers for AttributeDialog events.
		void OnOk(wxCommandEvent& event);
		void OnCancel(wxCommandEvent& event);
		void OnGroupSelected(wxCommandEvent& event);
		void OnItemChanged(wxCommandEvent& event);
	public:
		/** Constructor */
		AttributeDialogImpl(wxWindow* parent);
		//// end generated class members
		Core::Pointer<SceneModule::IAttribute> GetAttribute() {
			return m_attribute;
		}

		Core::Pointer<Core::IObject> CreateObject();
	private:
		AttributePanelImpl* m_attributes_panel;
		Core::Pointer<SceneModule::IAttribute> m_attribute;
	};
}

PUNK_ENGINE_END

#endif // __attribute_dialog_impl__
