//#ifndef __EngineModuleManagerAttributePanel__
//#define __EngineModuleManagerAttributePanel__
//
///**
//@file
//Subclass of AttributePanel, which is generated by wxFormBuilder.
//*/
//
//#include "forms.h"
//
////// end generated include
//
///** Implementing AttributePanel */
//class EngineModuleManagerAttributePanel : public AttributePanel
//{
//	public:
//		/** Constructor */
//		EngineModuleManagerAttributePanel( wxWindow* parent );
//	//// end generated class members
//	
//};
//
//#endif // __EngineModuleManagerAttributePanel__
