#ifndef __integer_editor_impl__
#define __integer_editor_impl__

/**
@file
Subclass of IntegerEditor, which is generated by wxFormBuilder.
*/

#include "forms.h"
#include <config.h>
#include <string/module.h>

//// end generated include

PUNK_ENGINE_BEGIN
namespace Tools {
	/** Implementing IntegerEditor */
	class IntegerEditorImpl : public IntegerEditor
	{
	protected:
		// Handlers for IntegerEditor events.
		void OnValueChanged(wxCommandEvent& event);
	public:
		/** Constructor */
		IntegerEditorImpl(wxWindow* parent);
		//// end generated class members
		void SetSourceValue(const Core::String& name, int* value);

	private:
		int* m_int;
	};
}
PUNK_ENGINE_END

#endif // __integer_editor_impl__
