//#ifndef __m_attribute_panel_impl__
//#define __m_attribute_panel_impl__
//
///**
//@file
//Subclass of AttributePanel, which is generated by wxFormBuilder.
//*/
//
//#include "forms.h"
//
////// end generated include
//
///** Implementing AttributePanel */
//class AttributePanelName : public AttributePanel
//{
//	public:
//		/** Constructor */
//		AttributePanelName( wxWindow* parent );
//	//// end generated class members
//	
//};
//
//#endif // __m_attribute_panel_impl__
