#ifndef __mat3_float_editor_impl__
#define __mat3_float_editor_impl__

/**
@file
Subclass of Mat3FloatEditor, which is generated by wxFormBuilder.
*/

#include "forms.h"
#include <config.h>
#include <core/value_monitor.h>
#include <math/forward.h>
#include <string/string.h>

//// end generated include

PUNK_ENGINE_BEGIN
namespace Tools {
	/** Implementing Mat3FloatEditor */
	class Mat3FloatEditorImpl : public Mat3FloatEditor
	{
	protected:
		// Handlers for Mat3FloatEditor events.
		void On0Changed(wxCommandEvent& event);
		void On3Changed(wxCommandEvent& event);
		void On6Changed(wxCommandEvent& event);
		void On1Changed(wxCommandEvent& event);
		void On4Changed(wxCommandEvent& event);
		void On7Changed(wxCommandEvent& event);
		void On2Changed(wxCommandEvent& event);
		void On5Changed(wxCommandEvent& event);
		void On8Changed(wxCommandEvent& event);
	public:
		/** Constructor */
		Mat3FloatEditorImpl(wxWindow* parent);
		virtual ~Mat3FloatEditorImpl();
		//// end generated class members
		void SetSourceValue(const Core::String& name, Core::ValueMonitor<Math::mat3>* value);
		void UpdateGui(const Math::mat3& value);
	private:
		Core::ValueMonitor<Math::mat3>* m_value;
	};
}
PUNK_ENGINE_END

#endif // __mat3_float_editor_impl__
