#ifndef __mat4_float_editor_impl__
#define __mat4_float_editor_impl__

/**
@file
Subclass of Mat4FloatEditor, which is generated by wxFormBuilder.
*/

#include "forms.h"
#include <math/forward.h>
#include <core/value_monitor.h>
#include <string/string.h>
#include <config.h>
//// end generated include

PUNK_ENGINE_BEGIN
namespace Tools {
	/** Implementing Mat4FloatEditor */
	class Mat4FloatEditorImpl : public Mat4FloatEditor
	{
	protected:
		
		// Handlers for Mat4FloatEditor events.
		void On0Changed(wxCommandEvent& event);
		void On4Changed(wxCommandEvent& event);
		void On8Changed(wxCommandEvent& event);
		void On12Changed(wxCommandEvent& event);
		void On1Changed(wxCommandEvent& event);
		void On5Changed(wxCommandEvent& event);
		void On9Changed(wxCommandEvent& event);
		void On13Changed(wxCommandEvent& event);
		void On2Changed(wxCommandEvent& event);
		void On6Changed(wxCommandEvent& event);
		void On10Changed(wxCommandEvent& event);
		void On14Changed(wxCommandEvent& event);
		void On3Changed(wxCommandEvent& event);
		void On7Changed(wxCommandEvent& event);
		void On11Changed(wxCommandEvent& event);
		void On15Changed(wxCommandEvent& event);
	public:
		/** Constructor */
		Mat4FloatEditorImpl(wxWindow* parent);
		virtual ~Mat4FloatEditorImpl();
		//// end generated class members
		void SetSourceValue(const Core::String& name, Core::ValueMonitor<Math::mat4>* value);
		void UpdateGui(const Math::mat4& value);
	private:
		Core::ValueMonitor<Math::mat4>* m_value;
	};
}
PUNK_ENGINE_END

#endif // __mat4_float_editor_impl__
