#ifndef __quat_float_editor_impl__
#define __quat_float_editor_impl__

/**
@file
Subclass of QuatFloatEditor, which is generated by wxFormBuilder.
*/

#include "forms.h"
#include <math/forward.h>
#include <core/value_monitor.h>
#include <string/string.h>

#include <config.h>
//// end generated include

PUNK_ENGINE_BEGIN
namespace Tools {
	/** Implementing QuatFloatEditor */
	class QuatFloatEditorImpl : public QuatFloatEditor
	{
	protected:
		// Handlers for QuatFloatEditor events.
		void OnWChanged(wxCommandEvent& event);
		void OnXChanged(wxCommandEvent& event);
		void OnYChanged(wxCommandEvent& event);
		void OnZChanged(wxCommandEvent& event);
	public:
		/** Constructor */
		QuatFloatEditorImpl(wxWindow* parent);
		virtual ~QuatFloatEditorImpl();
		//// end generated class members
		void SetSourceValue(const Core::String& name, Core::ValueMonitor<Math::quat>* value);
		void UpdateGui(const Math::quat& value);
	private:
		Core::ValueMonitor<Math::quat>* m_value;
	};
}
PUNK_ENGINE_END

#endif // __quat_float_editor_impl__
