#ifndef __string_editor_impl__
#define __string_editor_impl__

/**
@file
Subclass of StringEditor, which is generated by wxFormBuilder.
*/

#include "forms.h"
#include <core/value_monitor.h>
#include <config.h>
#include <string/string.h>
//// end generated include

PUNK_ENGINE_BEGIN
namespace Tools {
	/** Implementing StringEditor */
	class StringEditorImpl : public StringEditor
	{
	protected:
		// Handlers for StringEditor events.
		void OnValueChanged(wxCommandEvent& event);
	public:
		/** Constructor */
		StringEditorImpl(wxWindow* parent);
		virtual ~StringEditorImpl();
		//// end generated class members
		void SetSourceValue(const Core::String& name, Core::ValueMonitor<Core::String>* value);
		void UpdateGui(const Core::String& value);
	private:
		Core::ValueMonitor<Core::String>* m_str;
	};
}
PUNK_ENGINE_END

#endif // __string_editor_impl__
