#ifndef __vec2_float_editor_impl__
#define __vec2_float_editor_impl__

/**
@file
Subclass of Vec2FloatEditor, which is generated by wxFormBuilder.
*/

#include "forms.h"
#include <core/value_monitor.h>
#include <math/forward.h>
#include <string/string.h>
#include <config.h>
//// end generated include

PUNK_ENGINE_BEGIN
namespace Tools {
	/** Implementing Vec2FloatEditor */
	class Vec2FloatEditorImpl : public Vec2FloatEditor
	{
	protected:
		// Handlers for Vec2FloatEditor events.
		void OnXChanged(wxCommandEvent& event);
		void OnYChanged(wxCommandEvent& event);
	public:
		/** Constructor */
		Vec2FloatEditorImpl(wxWindow* parent);
		virtual ~Vec2FloatEditorImpl();
		//// end generated class members
		void SetSourceValue(const Core::String& name, Core::ValueMonitor<Math::vec2>* value);
		void UpdateGui(const Math::vec2& value);
	private:
		Core::ValueMonitor<Math::vec2>* m_value;
	};
}
PUNK_ENGINE_END

#endif // __vec2_float_editor_impl__
