#ifndef __vec4_float_editor_impl__
#define __vec4_float_editor_impl__

/**
@file
Subclass of Vec4FloatEditor, which is generated by wxFormBuilder.
*/

#include "forms.h"
#include <core/value_monitor.h>
#include <math/forward.h>
#include <string/string.h>
#include <config.h>

//// end generated include

PUNK_ENGINE_BEGIN
namespace Tools {
	/** Implementing Vec4FloatEditor */
	class Vec4FloatEditorImpl : public Vec4FloatEditor
	{
	public:
		/** Constructor */
		Vec4FloatEditorImpl(wxWindow* parent);
		virtual ~Vec4FloatEditorImpl();
		//// end generated class members

		void OnXChanged(wxCommandEvent& event);
		void OnYChanged(wxCommandEvent& event);
		void OnZChanged(wxCommandEvent& event);
		void OnWChanged(wxCommandEvent& event);		
		void SetSourceValue(const Core::String& name, Core::ValueMonitor<Math::vec4>* value);
		void UpdateGui(const Math::vec4& value);
	private:
		Core::ValueMonitor<Math::vec4>* m_value;
	};
}
PUNK_ENGINE_END

#endif // __vec4_float_editor_impl__
