######################################################################
# Automatically generated by qmake (2.01a) ?? 25. ??? 19:53:26 2013
######################################################################

include(../punk_common.pri)

CONFIG += dll
TEMPLATE = lib
TARGET = punk_scene

LIBS += -L$${LIBDIR} -lpunk_error -lpunk_string -lpunk_core -lpunk_system -lpunk_image -lpunk_math -lpunk_attributes

INCLUDEPATH += ../../../source

HEADERS += \
    ../../../source/scene/singlethreaded/attribute.h \
    ../../../source/scene/singlethreaded/command.h \
    ../../../source/scene/singlethreaded/iattribute.h \
    ../../../source/scene/singlethreaded/inode.h \
    ../../../source/scene/singlethreaded/iprocessor.h \
    ../../../source/scene/singlethreaded/iscene.h \
    ../../../source/scene/singlethreaded/iscene_builder.h \
    ../../../source/scene/singlethreaded/iscene_manager.h \
    ../../../source/scene/singlethreaded/iscene_observer.h \
    ../../../source/scene/singlethreaded/iscene_worker.h \
    ../../../source/scene/singlethreaded/module.h \
    ../../../source/scene/singlethreaded/node.h \
    ../../../source/scene/singlethreaded/node_state.h \
    ../../../source/scene/singlethreaded/scene.h \
    ../../../source/scene/singlethreaded/scene_helper.h \
    ../../../source/scene/singlethreaded/scene_manager.h \
    ../../../source/scene/singlethreaded/scene_manipulator.h \
    ../../../source/scene/singlethreaded/scene_processor.h \
    ../../../source/scene/singlethreaded/scene_worker.h \
    ../../../source/scene/module.h

SOURCES += \    
    ../../../source/scene/singlethreaded/attribute.cpp \
    ../../../source/scene/singlethreaded/command.cpp \
    ../../../source/scene/singlethreaded/graph_processor.cpp \
    ../../../source/scene/singlethreaded/node.cpp \
    ../../../source/scene/singlethreaded/scene.cpp \
    ../../../source/scene/singlethreaded/scene_helper.cpp \
    ../../../source/scene/singlethreaded/scene_manager.cpp \
    ../../../source/scene/singlethreaded/scene_processor.cpp \
    ../../../source/scene/singlethreaded/scene_worker.cpp

